### ISSUE TITLE
Can't set new twitch alerts

### ISSUE THREAD

**Issue by Nama** [Harfeur/Harfeur-Bots#1]
This is always true, I can't set any new alerts:
https://github.com/Harfeur/Harfeur-Bots/blob/a17fb82b85a02eab88fad5771a95fbc76d8274c8/discord_bots/twitchbot.js#L208

How can this be not "GUILD_TEXT"? To avoid DMs? I'm running the command in a channel of a server.

**Comment by Harfeur** [comment]
Hi! Thanks for the report. You can use slash commands while I'm fixing this issue
